feat: bootstrap yandex db
picodata/stroppy pull request #105
Opened 2022-08-26 09:32 UTC by DmitryTravyan

closes issue #101
closes issue #95

- implementation customTxTransfer
- partial refactoring for establishing secure ssh tunnels
- major improvements in interaction inside cluster

2022-08-30 13:27 UTC, VifleY requested changes

2022-08-30 13:27 UTC, VifleY commented on pkg/database/cluster/yandex.go
> +	ydbConnection ydb.Connection
`YandexDBCluster` содержит `ydbConnection` - кажется, избыточная информативность :) Я бы предложил просто `conn`

2022-08-30 13:27 UTC, VifleY commented on pkg/database/cluster/yandex.go
> +				//nolint:wrapcheck // linter does not understand then wrapped from external library
Настрой, пожалуйста, `wrapcheck`, если уж ты не хочешь его отключать
https://github.com/tomarrell/wrapcheck#configuration

2022-08-30 13:27 UTC, VifleY commented on pkg/engine/kubeengine/deploy_objects.go
> +func (k8sEngine *Engine) toEngineOnject(
Нужно ли нам это в этом МРе?

2022-08-30 13:27 UTC, VifleY commented on pkg/engine/kubeengine/ssh_tunnels_ports.go
> +			fmt.Sprintf("Because we starting ssh tunell for '%s' and port '%d' ",
Странная запись в логе. Давай её перефразируем, потому что я её не понимаю

2022-08-30 13:27 UTC, VifleY commented on pkg/engine/stroppy/pod.go
> +	deployContext, cancel := context.WithCancel(context.Background())
А зачем мы создаем его тут? Мы же не прокидываем его никуда до собственно вызова куба и из-за этого нам приходится дальше везде вставлять вызов `cancel`
Давай просто создавать его перед apply

2022-08-30 13:27 UTC, VifleY commented on pkg/engine/stroppy/pod.go
> +	deployContext, cancel := context.WithCancel(context.Background())
Аналогично замечанию выше

2022-08-31 17:40 UTC, DmitryTravyan commented on pkg/database/cluster/yandex.go
> +				//nolint:wrapcheck // linter does not understand then wrapped from external library
Будет исправлено в https://github.com/picodata/stroppy/pull/109

2022-08-31 17:48 UTC, DmitryTravyan commented on pkg/engine/stroppy/pod.go
> +	deployContext, cancel := context.WithCancel(context.Background())
В MR https://github.com/picodata/stroppy/pull/106 эта часть полность переработана.

2022-08-31 17:49 UTC, DmitryTravyan commented on pkg/engine/stroppy/pod.go
> +	deployContext, cancel := context.WithCancel(context.Background())
В MR https://github.com/picodata/stroppy/pull/106 эта часть полность переработана.

2022-08-31 17:50 UTC, DmitryTravyan commented on pkg/database/cluster/yandex.go
> +	ydbConnection ydb.Connection
исправил на conn

2022-08-31 17:50 UTC, DmitryTravyan commented on pkg/engine/kubeengine/deploy_objects.go
> +func (k8sEngine *Engine) toEngineOnject(
Была заготовка на следующий MR. Убрать из этого?

2022-08-31 17:50 UTC, DmitryTravyan commented on pkg/engine/kubeengine/ssh_tunnels_ports.go
> +			fmt.Sprintf("Because we starting ssh tunell for '%s' and port '%d' ",
Поправил запись

2022-08-31 18:23 UTC, VifleY commented on pkg/engine/kubeengine/deploy_objects.go
> +func (k8sEngine *Engine) toEngineOnject(
да, у нас и так большие MRы, давай постараемся хотя бы так минимизировать

2022-08-31 18:24 UTC, VifleY approved these changes

2022-08-31 18:26 UTC, merged