107 realize pop
picodata/stroppy pull request #109
Opened 2022-08-31 17:35 UTC by DmitryTravyan

2022-09-02 17:15 UTC, VifleY requested changes

2022-09-02 17:15 UTC, VifleY commented on internal/deployment/constants.go
> +	testsDirPath   = "third_party/tests"
Неудачное название. Предлагаю `testsConfigurationDir` или `testConfDir`

2022-09-02 17:15 UTC, VifleY commented on build/Dockerfile
> +    && apt install -y ca-certificates wget curl python3 pip unzip ssh vim \
А зачем вим? Для удобства отладки?

2022-09-02 17:15 UTC, VifleY commented on internal/deployment/constants.go
> +	testsDirPath   = "third_party/tests"
Неудачное название. Предлагаю `testsConfDir` или `testsConfigurationDir` или что-то похожее

2022-09-02 17:15 UTC, VifleY commented on pkg/database/cluster/yandex.go
> +	defer connClose()
А это завершение запроса или закрытие `connection`?

2022-09-02 17:15 UTC, VifleY commented on pkg/database/cluster/yandex.go
> +	defer connClose()
Судя по godoc - это завершение запроса. Переименуй, пожалуйста, или подскажи, где я не прав

2022-09-02 17:15 UTC, VifleY commented on pkg/database/cluster/yandex.go
> +	ydbContext, connClose := context.WithCancel(context.Background())
Собственно, зачем тебе `context.WithCancel`, если ты не зовешь его по таймауту / дедлайну?

2022-09-02 17:19 UTC, DmitryTravyan commented on internal/deployment/constants.go
> +	testsDirPath   = "third_party/tests"
поменял на testConfDir

2022-09-02 17:19 UTC, DmitryTravyan commented on build/Dockerfile
> +    && apt install -y ca-certificates wget curl python3 pip unzip ssh vim \
ага, а то там вообще нет никакого текстового редактора

2022-09-02 17:42 UTC, DmitryTravyan commented on pkg/database/cluster/yandex.go
> +	ydbContext, connClose := context.WithCancel(context.Background())
Поменял на WithTimeout

2022-09-02 17:43 UTC, DmitryTravyan commented on pkg/database/cluster/yandex.go
> +	defer connClose()
Поменял, ты прав. Корректнее было бы назвать ctxCancelFn

2022-09-02 18:59 UTC, DmitryTravyan commented on internal/deployment/constants.go
> +	testsDirPath   = "third_party/tests"
поменял на testsConfDir

2022-09-05 07:36 UTC, VifleY approved these changes

2022-09-05 07:36 UTC, merged