pop logic fixes
picodata/stroppy pull request #141
Opened 2022-10-11 18:23 UTC by DmitryTravyan

Fixed:
- race condition on errors in BasePayload.Pop(),
- bic+ban are now re-generated on duplicate key

2022-10-12 17:47 UTC, VifleY requested changes

2022-10-12 17:47 UTC, VifleY commented on internal/payload/pop.go
>  				if err = p.Cluster.InsertAccount(acc); err != nil {
с ребейзом ушел shadowing и фактически пропал фикс race condition

2022-10-13 07:08 UTC, DmitryTravyan commented on internal/payload/pop.go
>  				if err = p.Cluster.InsertAccount(acc); err != nil {
исправил

2022-10-13 07:42 UTC, VifleY approved these changes

2022-10-13 07:43 UTC, merged