Feat(cockroach) test gen support
picodata/stroppy pull request #19
Opened 2021-11-15 06:39 UTC by al-andreev

2021-11-18 09:13 UTC, niksav555 requested changes

2021-11-24 06:33 UTC, al-andreev commented on docs/examples/deploy-oracle-3node-2cpu-8gbRAM-100gbStorage/databases/cockroach/operator/crds.yaml
>                    key for the TLS endpoint on the database port. The standard naming
Таково требование производителя - его надо использовать перед вторым yaml файлом

2021-11-24 06:34 UTC, al-andreev commented on docs/examples/deploy-oracle-5node-1cpu-8gbRAM-100gbStorage/databases/cockroach/_insecure/cockroachdb-statefulset.yaml
> +apiVersion: v1
Посмотрел - лучше не надо, поскольку надо будет править несколько файлов, к тому же конфиг с пятью узлами более интересен чем с тремя

2021-11-24 06:35 UTC, al-andreev commented on docs/examples/deploy-oracle-5node-1cpu-8gbRAM-100gbStorage/databases/cockroach/crdb.yaml
> +#    worker-type: dbms-worker
Поправил

2021-11-24 06:35 UTC, al-andreev commented on docs/examples/deploy-oracle-3node-2cpu-8gbRAM-100gbStorage/databases/cockroach/_insecure/cockroachdb-statefulset-insecure.yaml
> +          storage: 1024Gi
Поправил

2021-11-24 08:06 UTC, niksav555 approved these changes

2021-11-25 14:40 UTC, niksav555 commented on docs/examples/deploy-oracle-5node-1cpu-8gbRAM-100gbStorage/databases/cockroach/_insecure/cockroachdb-statefulset.yaml
> +apiVersion: v1
Уточни, пожалуйста, какие файлы ты имеешь ввиду? Мы можем оставить только варианты с 5-ю узлами, разницы нет, но 3-узловая - как раз такая минимальная конфигурация, с которой можно начать  "из коробки".

2021-11-26 06:18 UTC, merged