feat(stroppy): add tests of methods BootstrapDB() and NewMongoDBCluster()
picodata/stroppy pull request #20
Opened 2021-11-24 15:38 UTC by niksav555

2021-11-24 15:40 UTC, niksav555 commented
пока драфт

2021-11-25 14:05 UTC, niksav555 commented
> пока драфт

@al-andreev , можно смотреть

2021-11-26 06:30 UTC, al-andreev requested changes

2021-11-26 06:30 UTC, al-andreev commented on pkg/database/cluster/mongo_test.go
> +var receivedAccount bson.M
Не принципиально, но лучше бы обьединить в один блок var

2021-11-26 06:30 UTC, al-andreev commented on pkg/database/cluster/mongo_test.go
> +func TestBootstrapDB(t *testing.T) {
Предлагаю тебе сделать тестовый метод с таким названием на более общим, который вызывал бы методы TestMongoBootstrap, TestPostgresBootstrap итд.

2021-11-26 06:30 UTC, al-andreev commented on pkg/database/cluster/mongo_test.go
> +	for _, coll := range collNames {
Ты в этом тесте повторяешь код работы с выборкой который уже есть в основном методе проверки баланса в типе mongoCluster? Тогда стоит подумать над тем, что бы сделать рефакторинг, метод Check везде разбить на два метода, что бы в обобщенной функции TestBootstrapDB() сначала вызывать 
_some_Cluster.BootstrapDB(), потом например _some_Cluster.RetrieveData()

2021-11-26 06:30 UTC, al-andreev commented on pkg/database/cluster/mongo_test.go
> +	opts := options.Find().SetSort(bson.D{primitive.E{Key: "_id", Value: 1}}).SetProjection(bson.M{"_id": 0})
Аналогично здесь - у тебя этот метод должен тестировать реализацию которая есть в основном пакете, а в данном случае предлагается своя тестовая реализация (повторяющая то что есть в основном типе), так не надо делать.

2021-11-26 14:41 UTC, niksav555 commented on pkg/database/cluster/mongo_test.go
> +	for _, coll := range collNames {
Я cделал общие вызовы в cluster_test.go, чтобы было удобнее вызывать и добавлять новые тесты, но предлагаю на текущем этапе не разделять логику проверки и сам вызов тестируемого метода, т.к. проверки индивидуальны для каждого из методов. Если разделить, то будет сложнее читать, т.к. придется переключаться между тремя функциями вместо двух.

2021-11-26 14:44 UTC, niksav555 commented on pkg/database/cluster/mongo_test.go
> +	for _, coll := range collNames {
Код работы с выборкой переиспользуется, потому что он уже есть) Но в другом методе.
В любом случае, мне нужно в тесте проверить, что все действия, выполненные тестируемой функцией, выполнены, как ожидалось. Поэтому логично, что какие-то методы проверки будут похожи на то, что есть уже в базовом коде, но вызываться в другом методе.

2021-11-29 06:38 UTC, al-andreev approved these changes

2021-11-29 08:31 UTC, merged