feat(stroppy): add getting of monitoring data for several clusters on one user machine
picodata/stroppy pull request #23
Opened 2021-11-26 11:47 UTC by niksav555

Added new parameter "port" in getting data function CollectMonitoringData() for getting data from other clusters.
Parameters of ports for monitoring and kubernetes renamed and had become exportable for using in CollectMonitoringData().
Method GetInfraports() deleted, because it is not needed anymore.

2021-11-29 06:34 UTC, al-andreev requested changes

2021-11-29 06:34 UTC, al-andreev commented on pkg/kubernetes/definitions.go
> +	KubernetesPort *ssh.Result
Не вижу, что бы эти константы использовались вне пакета - сделай их приватными

2021-11-29 08:38 UTC, niksav555 commented on pkg/kubernetes/definitions.go
> +	KubernetesPort *ssh.Result
Они используются в internal/deployment и были приватными.
Но вызывать из 5-х разных мест функцию GetInfraPorts() вместо обращение к экспортируемой переменной показалось более накладным.

2021-12-07 06:57 UTC, al-andreev approved these changes

2021-12-07 09:31 UTC, merged