Separate workers count and connect pool
picodata/stroppy pull request #43
Opened 2021-12-26 20:44 UTC by niksav555

Вместо add-pool добавлен параметр pool-size, который определяет кол-во соединений для pg, cocroach и mongo,
Если не задан, то пул равен кол-ву воркеров. Если задан одновременно с max_pool_size для pg и cocroach, то применяется max_pool_size

2021-12-28 07:17 UTC, VifleY requested changes

2021-12-28 07:17 UTC, VifleY commented on pkg/database/cluster/postgres.go
> +	if !strings.Contains(dbURL, "pool_max_conns") {
А в pg драйвере нет встроенного метода для парсинга строки подключения?

2021-12-28 07:17 UTC, VifleY commented on pkg/database/cluster/postgres.go
> +	llog.Infoln("размер пула", poolConfig.MaxConns)
Плохой сообщение для лога - непонятно, что за размер пула и когда мы его логгируем + остальные логи на английском, кажется

2021-12-28 07:17 UTC, VifleY commented on pkg/database/config/defsettings.go
> +	ConnectPoolCount   int
ConnectionPoolSize

2021-12-28 07:17 UTC, VifleY commented on pkg/database/cluster/cockroach.go
> +func NewCockroachCluster(dbURL string, dbPool int) (cluster *CockroachDatabase, err error) {
`dbPool` - плохое название. Главная претензия в том, что название говорит о том, что это действительно пул, когда это всего лишь его размер

Как и ниже - предлагаю `connectionPoolSize`

2021-12-28 07:18 UTC, niksav555 commented on pkg/database/cluster/postgres.go
> +	llog.Infoln("размер пула", poolConfig.MaxConns)
это отладочное, уберу или спрячу в debug

2021-12-29 08:14 UTC, niksav555 commented on pkg/database/cluster/postgres.go
> +	if !strings.Contains(dbURL, "pool_max_conns") {
Есть конструкция вида config.ConnConfig.Config.RuntimeParams["pool_max_conns"], но, если она true
pgxpool.ParseConfig(dbURL), то удаляет зачем-то параметр из мапы перед присвоением значения.

2021-12-30 12:41 UTC, VifleY approved these changes

2021-12-30 12:49 UTC, merged