test(cluster): add cockroach test
picodata/stroppy pull request #67
Opened 2022-03-23 14:28 UTC by YuriyVodyasov

Close #15

2022-03-23 21:09 UTC, niksav555 reviewed
Go test лучше запустить внутри папки с cluster_test.go, только тесты должны подхватиться. Для выполнения тестов только одной из бд лучше сделать какой-нибудь флаг для выбора. Когда писались первые тесты, я, к сожалению, этого не сделал. Можно оставить как есть, сделаю чуть позже, когда вольешь свой мр

2022-04-01 14:51 UTC, VifleY requested changes

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach.go
> +			return merry.Prepend(err, "failed to withdraw money 0")
Нужно нормальное сообщение об ошибке - например, что не смог снять деньги, а во втором случае, что не смог начислить
Или какой-то другой идентификатор (не циферка 1 / 0)

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +const cockroachDBUrl = "postgresql://root@Raider:26257/defaultdb?sslmode=disable" // TODO: уточнить ссылку
Нужно брать из переменной окружения

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +const cockroachDBUrl = "postgresql://root@Raider:26257/defaultdb?sslmode=disable" // TODO: уточнить ссылку
Нужно брать из переменной окружения, а если нет - подставлять дефолтную

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cluster_test.go
> +	mongoDBUrl                = "mongodb://127.0.0.1:27017/stroppy" //30001,127.0.0.1:30002,127.0.0.1:30003/stroppy"
Нужно брать из переменной окружения, а если нет - подставлять дефолтную

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cluster_test.go
> +	mongoDBUrl                = "mongodb://127.0.0.1:27017/stroppy" //30001,127.0.0.1:30002,127.0.0.1:30003/stroppy"
Нужно брать из переменной окружения

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +		Ban).Scan(
Предлагаю всё-таки писать:
```
Ban,
).Scan(
...

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +		Ban).Scan(
Предлагаю всё-таки писать:
```
Ban,
).Scan(
...

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +		t.Errorf("NewTestCockroachCluster() received internal error  %s, but expected nil", err)
Это `t.Fatal`, по идее

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +		t.Errorf("NewTestCockroachCluster() received internal error  %s, but expected nil", err)
Это `t.Fatal`, по идее

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +func CockroachBootstrapDB(t *testing.T) {
Если в бутстрапе создаются таблицы, то их наличие тоже нужно проверить

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +func CockroachBootstrapDB(t *testing.T) {
Если в бутстрапе создаются таблицы, то их наличие тоже нужно проверить

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +	if count != 0 {
Эти все сравнения нужно заменить `assert`ами

2022-04-01 14:51 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +	if count != 0 {
Эти все сравнения нужно заменить `assert`ами

2022-04-12 16:49 UTC, VifleY reviewed
добавь, пожалуйста, Cockroach в docker-compose.template.yml

2022-04-13 10:38 UTC, VifleY approved these changes

2022-04-13 11:26 UTC, merged