test(cluster): add foundation db unit test
picodata/stroppy pull request #71
Opened 2022-04-12 11:16 UTC by YuriyVodyasov

2022-04-12 16:53 UTC, VifleY requested changes

2022-04-12 16:53 UTC, VifleY commented on pkg/database/cluster/fdb_test.go
> +	// TODO: implement me
Нужно доделать

2022-04-12 16:53 UTC, VifleY commented on pkg/database/cluster/fdb_test.go
> +	// TODO: refactor this
нужно отрефакторить, либо дропнуть коммент

2022-04-15 09:08 UTC, VifleY requested changes

2022-04-15 09:08 UTC, VifleY commented on pkg/database/cluster/cockroach_test.go
> +func (cockroach *CockroachDatabase) GetAccount(Bic string, Ban string) (Account model.Account, err error) {
Почему в МР по foundation изменения в тесты cockroach?

2022-04-15 11:49 UTC, YuriyVodyasov commented on pkg/database/cluster/cockroach_test.go
> +func (cockroach *CockroachDatabase) GetAccount(Bic string, Ban string) (Account model.Account, err error) {
Уехало в отдельную ветку (MR скоро)

2022-04-22 16:19 UTC, VifleY commented on pkg/database/cluster/mongo.go
> +	clientOptions.SetDirect(true)
сломает работу с кластером
https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo/options#ClientOptions.SetDirect

2022-04-26 10:48 UTC, merged